### PR TITLE
update for FF37a2

### PR DESCRIPTION
**Pull request by tejanium**
- https://github.com/piroor/textlink/issues/43 remove .quote()
- https://github.com/piroor/textlink/issues/44 up to Firefox 37a2

### CODE REVIEW

**Comment by yfdyh000** [comment]
@piroor plz merge and update to AMO.

**Comment by mzso** [comment]
@tejanium commented on [2015. febr. 13. 5:04 CET](https://github.com/piroor/textlink/pull/45#issue-57556679 "2015-02-13T04:04:13Z - Replied by Github Comment Enhancer"):
> *   [#43](https://github.com/piroor/textlink/issues/43 "String.prototype.quote has been completely removed in Firefox 37") remove .quote()
> *   [#44](https://github.com/piroor/textlink/issues/44 "Stopped working completely on Mozillla central.") up to Firefox 37a2

Hello!
Seeing as the author is missing can you provide a build here on github?

**Comment by tejanium** [comment]
Hi @mzso please take a look at https://github.com/tejanium/textlink/commit/437c553d663a4b01c51c41b081acbabfc1aeec1b

**Comment by mzso** [comment]
Great!

**Comment by piroor** [comment]
Sorry, I forgot to see this...
Equivalent changes are already introduced, so I close this.

**Pull request closed without merging**
